# IUM FILM DATA CLEANING AND EDA
 placeholder

## Step 0: Imports and Data

#### Importing Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('fivethirtyeight')
pd.set_option('display.max_columns', 150)

#### Importing data

In [3]:
df_movies = pd.read_csv("data/main_data/movies.csv")
df_actors = pd.read_csv("data/main_data/actors.csv")
df_countries = pd.read_csv("data/main_data/countries.csv")
df_crew = pd.read_csv("data/main_data/crew.csv")
df_genres = pd.read_csv("data/main_data/genres.csv")
df_languages = pd.read_csv("data/main_data/languages.csv")
df_posters = pd.read_csv("data/main_data/posters.csv")
df_releases = pd.read_csv("data/main_data/releases.csv")
df_studios = pd.read_csv("data/main_data/studios.csv")
df_themes = pd.read_csv("data/main_data/themes.csv")

## Data cleaning
movies

In [12]:
df_movies.shape

(937468, 7)

In [5]:
df_movies.head()

,id,name,date,tagline,description,minute,rating
0,1000001,Barbie,2023.0,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114.0,3.86
1,1000002,Parasite,2019.0,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133.0,4.56
2,1000003,Everything Everywhere All at Once,2022.0,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140.0,4.30
3,1000004,Fight Club,1999.0,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139.0,4.27
4,1000005,La La Land,2016.0,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129.0,4.09

In [17]:
df_movies.loc[df_movies.duplicated(subset=["name","date","description","minute"])]

,id,name,date,tagline,description,minute,rating
73818,1073819,Better Than Sex,2000.0,3 days in the life of a 1 night stand.,After a one-night stand a couple is faced with...,84.0,3.24
73819,1073820,Amoklauf,1994.0,NaN,A nameless waiter spends his days sitting arou...,65.0,NaN
73821,1073822,Still Working 9 to 5,2022.0,NaN,Examines the 40-year evolution of gender inequ...,95.0,NaN
73822,1073823,Power On: The Story of Xbox,2021.0,Four gamers. One idea. And a billion dollar bet.,Xbox almost didn't happen. Find out why in thi...,NaN,3.61
73823,1073824,Crossing the Line,2006.0,NaN,"In 1962, a U.S. soldier sent to guard the peac...",94.0,3.44
...,...,...,...,...,...,...,...
940447,1940448,Riina - Le verità nascoste,2018.0,NaN,NaN,45.0,NaN
940455,1940456,Yen Ching 燕京,2018.0,NaN,An intergenerational dilemma between immigrant...,64.0,NaN
940492,1940493,Our Cinema Oscar Special LIVE,2017.0,NaN,Gregg Turkington and Mark Proksch continue the...,107.0,NaN
940592,1940593,Happy Birthday!,2013.0,NaN,'Misery' doesn't like 'company' -- but 'compan...,20.0,NaN
941149,1941150,Extraños,NaN,NaN,NaN,NaN,NaN

In [12]:
#Example
df_movies.query('name == "The Three Stooges"')

,id,name,date,tagline,description,minute,rating
9928,1009929,The Three Stooges,2012.0,No knuckleheads were harmed in the making of t...,While trying to save their childhood orphanage...,92.0,2.38
73815,1073816,The Three Stooges,2000.0,"Their comedy made us laugh out loud, but their...","A biography of the Three Stooges, in which the...",88.0,3.23
73825,1073826,The Three Stooges,2000.0,"Their comedy made us laugh out loud, but their...","A biography of the Three Stooges, in which the...",88.0,3.23

In [15]:
df_movies.duplicated(subset=["name","date","description","minute"]).sum()

np.int64(4129)

In [6]:
df_movies = df_movies.drop_duplicates(subset=["name","date","description","minute"], keep="first")

## Step 2: